// Map Mode fallback data.
// These connected nodes make a campus navigation game that works without Google Street View.
// Replace imageUrl and panoramaImageUrl values with real UCLA photos or 360 images later.

export const mapNodes = [
  {
    id: "janss-steps",
    name: "Janss Steps",
    latitude: 34.0716,
    longitude: -118.4426,
    imageUrl: "/campus-views/janss-steps.jpg",
    panoramaImageUrl: "/campus-views/janss-steps-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 90,
    pitch: 0,
    connections: {
      forward: "royce-hall",
      left: "powell-library",
      right: "bruin-plaza",
      back: "inverted-fountain",
    },
    type: "map",
  },
  {
    id: "royce-hall",
    name: "Royce Hall",
    latitude: 34.0728,
    longitude: -118.4421,
    imageUrl: "/campus-views/royce-hall.jpg",
    panoramaImageUrl: "/campus-views/royce-hall-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 180,
    pitch: 0,
    connections: {
      forward: "sculpture-garden",
      left: "young-research-library",
      right: "powell-library",
      back: "janss-steps",
    },
    type: "map",
  },
  {
    id: "powell-library",
    name: "Powell Library",
    latitude: 34.0719,
    longitude: -118.4418,
    imageUrl: "/campus-views/powell-library.jpg",
    panoramaImageUrl: "/campus-views/powell-library-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 270,
    pitch: 0,
    connections: {
      forward: "royce-hall",
      left: "kerckhoff-hall",
      right: "janss-steps",
      back: "bruin-plaza",
    },
    type: "map",
  },
  {
    id: "bruin-plaza",
    name: "Bruin Plaza",
    latitude: 34.0704,
    longitude: -118.4448,
    imageUrl: "/campus-views/bruin-plaza.jpg",
    panoramaImageUrl: "/campus-views/bruin-plaza-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 20,
    pitch: 0,
    connections: {
      forward: "bruin-bear",
      left: "kerckhoff-hall",
      right: "ackerman-union",
      back: "janss-steps",
    },
    type: "map",
  },
  {
    id: "bruin-bear",
    name: "Bruin Bear",
    latitude: 34.0703,
    longitude: -118.4452,
    imageUrl: "/campus-views/bruin-bear.jpg",
    panoramaImageUrl: "/campus-views/bruin-bear-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 80,
    pitch: 0,
    connections: {
      forward: "john-wooden-center",
      left: "ackerman-union",
      right: "bruin-plaza",
      back: "kerckhoff-hall",
    },
    type: "map",
  },
  {
    id: "ackerman-union",
    name: "Ackerman Union",
    latitude: 34.0702,
    longitude: -118.4449,
    imageUrl: "/campus-views/ackerman-union.jpg",
    panoramaImageUrl: "/campus-views/ackerman-union-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 160,
    pitch: 0,
    connections: {
      forward: "bruin-bear",
      left: "bruin-plaza",
      right: "pauley-pavilion",
      back: "kerckhoff-hall",
    },
    type: "map",
  },
  {
    id: "kerckhoff-hall",
    name: "Kerckhoff Hall",
    latitude: 34.0708,
    longitude: -118.4439,
    imageUrl: "/campus-views/kerckhoff-hall.jpg",
    panoramaImageUrl: "/campus-views/kerckhoff-hall-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 45,
    pitch: 0,
    connections: {
      forward: "powell-library",
      left: "bruin-plaza",
      right: "inverted-fountain",
      back: "ackerman-union",
    },
    type: "map",
  },
  {
    id: "inverted-fountain",
    name: "Inverted Fountain",
    latitude: 34.0707,
    longitude: -118.4401,
    imageUrl: "/campus-views/inverted-fountain.jpg",
    panoramaImageUrl: "/campus-views/inverted-fountain-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 210,
    pitch: 0,
    connections: {
      forward: "court-of-sciences",
      left: "kerckhoff-hall",
      right: "boelter-hall",
      back: "janss-steps",
    },
    type: "map",
  },
  {
    id: "court-of-sciences",
    name: "Court of Sciences",
    latitude: 34.0688,
    longitude: -118.4413,
    imageUrl: "/campus-views/court-of-sciences.jpg",
    panoramaImageUrl: "/campus-views/court-of-sciences-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 120,
    pitch: 0,
    connections: {
      forward: "boelter-hall",
      left: "engineering-vi",
      right: "inverted-fountain",
      back: "sculpture-garden",
    },
    type: "map",
  },
  {
    id: "boelter-hall",
    name: "Boelter Hall",
    latitude: 34.0689,
    longitude: -118.4428,
    imageUrl: "/campus-views/boelter-hall.jpg",
    panoramaImageUrl: "/campus-views/boelter-hall-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 300,
    pitch: 0,
    connections: {
      forward: "engineering-vi",
      left: "court-of-sciences",
      right: "inverted-fountain",
      back: "pauley-pavilion",
    },
    type: "map",
  },
  {
    id: "engineering-vi",
    name: "Engineering VI",
    latitude: 34.0697,
    longitude: -118.4423,
    imageUrl: "/campus-views/engineering-vi.jpg",
    panoramaImageUrl: "/campus-views/engineering-vi-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 180,
    pitch: 0,
    connections: {
      forward: "boelter-hall",
      left: "court-of-sciences",
      right: "pauley-pavilion",
      back: "inverted-fountain",
    },
    type: "map",
  },
  {
    id: "pauley-pavilion",
    name: "Pauley Pavilion",
    latitude: 34.0704,
    longitude: -118.4468,
    imageUrl: "/campus-views/pauley-pavilion.jpg",
    panoramaImageUrl: "/campus-views/pauley-pavilion-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 15,
    pitch: 0,
    connections: {
      forward: "john-wooden-center",
      left: "ackerman-union",
      right: "bruin-bear",
      back: "boelter-hall",
    },
    type: "map",
  },
  {
    id: "john-wooden-center",
    name: "John Wooden Center",
    latitude: 34.0717,
    longitude: -118.4466,
    imageUrl: "/campus-views/john-wooden-center.jpg",
    panoramaImageUrl: "/campus-views/john-wooden-center-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 210,
    pitch: 0,
    connections: {
      forward: "pauley-pavilion",
      left: "bruin-bear",
      right: "murphy-hall",
      back: "kaufman-area",
    },
    type: "map",
  },
  {
    id: "sculpture-garden",
    name: "Sculpture Garden",
    latitude: 34.0731,
    longitude: -118.4402,
    imageUrl: "/campus-views/sculpture-garden.jpg",
    panoramaImageUrl: "/campus-views/sculpture-garden-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 135,
    pitch: 0,
    connections: {
      forward: "court-of-sciences",
      left: "young-research-library",
      right: "royce-hall",
      back: "murphy-hall",
    },
    type: "map",
  },
  {
    id: "murphy-hall",
    name: "Murphy Hall",
    latitude: 34.0714,
    longitude: -118.4396,
    imageUrl: "/campus-views/murphy-hall.jpg",
    panoramaImageUrl: "/campus-views/murphy-hall-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 255,
    pitch: 0,
    connections: {
      forward: "sculpture-garden",
      left: "inverted-fountain",
      right: "john-wooden-center",
      back: "royce-hall",
    },
    type: "map",
  },
  {
    id: "young-research-library",
    name: "Young Research Library",
    latitude: 34.0742,
    longitude: -118.4415,
    imageUrl: "/campus-views/young-research-library.jpg",
    panoramaImageUrl: "/campus-views/young-research-library-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 190,
    pitch: 0,
    connections: {
      forward: "sculpture-garden",
      left: "royce-hall",
      right: "murphy-hall",
      back: "powell-library",
    },
    type: "map",
  },
  {
    id: "kaufman-area",
    name: "Kaufman Hall Area",
    latitude: 34.0724,
    longitude: -118.4460,
    imageUrl: "/campus-views/kaufman-area.jpg",
    panoramaImageUrl: "/campus-views/kaufman-area-panorama.jpg",
    streetViewPanoramaId: null,
    streetViewUrl: null,
    heading: 90,
    pitch: 0,
    connections: {
      forward: "john-wooden-center",
      left: "bruin-bear",
      right: "pauley-pavilion",
      back: "bruin-plaza",
    },
    type: "map",
  },
];

export function getMapNodeById(id) {
  return mapNodes.find((node) => node.id === id);
}
