// Picture Mode data.
// Replace these placeholder paths with your own UCLA photos.
// Put real images in public/campus-photos/ and reference them like:
// imageUrl: "/campus-photos/my-photo.jpg"

export const pictureLocations = [
  {
    id: "inside-powell-library",
    name: "Inside Powell Library",
    latitude: 34.0719,
    longitude: -118.4418,
    imageUrl: "/campus-photos/inside-powell-library.jpg",
    building: "Powell Library",
    hint: "A classic study spot near Dickson Plaza.",
    type: "picture",
  },
  {
    id: "inside-royce-hall",
    name: "Inside Royce Hall",
    latitude: 34.0728,
    longitude: -118.4421,
    imageUrl: "/campus-photos/inside-royce-hall.jpg",
    building: "Royce Hall",
    hint: "One of UCLA's most iconic performance and lecture buildings.",
    type: "picture",
  },
  {
    id: "inside-ackerman-union",
    name: "Inside Ackerman Union",
    latitude: 34.0702,
    longitude: -118.4449,
    imageUrl: "/campus-photos/inside-ackerman-union.jpg",
    building: "Ackerman Union",
    hint: "A busy student hub near Bruin Plaza.",
    type: "picture",
  },
  {
    id: "inside-kerckhoff-hall",
    name: "Inside Kerckhoff Hall",
    latitude: 34.0708,
    longitude: -118.4439,
    imageUrl: "/campus-photos/inside-kerckhoff-hall.jpg",
    building: "Kerckhoff Hall",
    hint: "Historic student spaces near the center of campus.",
    type: "picture",
  },
  {
    id: "inside-engineering-vi",
    name: "Inside Engineering VI",
    latitude: 34.0697,
    longitude: -118.4423,
    imageUrl: "/campus-photos/inside-engineering-vi.jpg",
    building: "Engineering VI",
    hint: "A South Campus engineering building.",
    type: "picture",
  },
  {
    id: "inside-boelter-hall",
    name: "Inside Boelter Hall",
    latitude: 34.0689,
    longitude: -118.4428,
    imageUrl: "/campus-photos/inside-boelter-hall.jpg",
    building: "Boelter Hall",
    hint: "A major engineering building connected to the Court of Sciences area.",
    type: "picture",
  },
  {
    id: "inside-john-wooden-center",
    name: "Inside John Wooden Center",
    latitude: 34.0717,
    longitude: -118.4466,
    imageUrl: "/campus-photos/inside-john-wooden-center.jpg",
    building: "John Wooden Center",
    hint: "A recreation and fitness building on the west side of campus.",
    type: "picture",
  },
  {
    id: "inside-young-research-library",
    name: "Inside Young Research Library",
    latitude: 34.0742,
    longitude: -118.4415,
    imageUrl: "/campus-photos/inside-young-research-library.jpg",
    building: "Young Research Library",
    hint: "A major library north of Royce and Powell.",
    type: "picture",
  },
  {
    id: "inside-kaufman-hall",
    name: "Inside Kaufman Hall",
    latitude: 34.0724,
    longitude: -118.4460,
    imageUrl: "/campus-photos/inside-kaufman-hall.jpg",
    building: "Kaufman Hall",
    hint: "Associated with dance and world arts spaces.",
    type: "picture",
  },
  {
    id: "inside-broad-art-center",
    name: "Inside Broad Art Center",
    latitude: 34.0752,
    longitude: -118.4409,
    imageUrl: "/campus-photos/inside-broad-art-center.jpg",
    building: "Broad Art Center",
    hint: "A North Campus arts building.",
    type: "picture",
  },
];
